-- Headless tests for SpriteTools (apps/sprite/tools.lua).

group("SpriteTools: lines in every direction, both ends included")
local L = SpriteTools.line_cells
eq(L(0, 0, 0, 0), { { 0, 0 } }, "a point is one cell")
eq(L(0, 0, 3, 0), { { 0, 0 }, { 1, 0 }, { 2, 0 }, { 3, 0 } }, "east")
eq(L(3, 0, 0, 0), { { 3, 0 }, { 2, 0 }, { 1, 0 }, { 0, 0 } }, "west")
eq(L(0, 0, 0, 2), { { 0, 0 }, { 0, 1 }, { 0, 2 } }, "south")
eq(L(0, 2, 0, 0), { { 0, 2 }, { 0, 1 }, { 0, 0 } }, "north")
eq(L(0, 0, 2, 2), { { 0, 0 }, { 1, 1 }, { 2, 2 } }, "south-east")
eq(L(2, 2, 0, 0), { { 2, 2 }, { 1, 1 }, { 0, 0 } }, "north-west")
eq(L(0, 2, 2, 0), { { 0, 2 }, { 1, 1 }, { 2, 0 } }, "north-east")
eq(L(2, 0, 0, 2), { { 2, 0 }, { 1, 1 }, { 0, 2 } }, "south-west")
eq(L(0, 0, 4, 2), { { 0, 0 }, { 1, 1 }, { 2, 1 }, { 3, 2 }, { 4, 2 } }, "a shallow line steps one cell at a time")

group("SpriteTools: pencil, eraser and mirror")
local d = SpriteDoc.blank(4, 2)
SpriteTools.paint(d, 0, 0, "1", false)
eq(d:rows(), { "1...", "...." }, "paint sets one cell")
SpriteTools.paint(d, 1, 1, "2", true)
eq(d:rows(), { "1...", ".22." }, "mirror also sets the cell mirrored across the centre")
SpriteTools.paint(d, 0, 0, ".", true)
eq(d:rows(), { "....", ".22." }, "the eraser paints '.'")
SpriteTools.stroke(d, 0, 0, 3, 0, "3", false)
eq(d:rows()[1], "3333", "a stroke fills the gap between two samples")
SpriteTools.stroke(d, 0, 1, 1, 1, "4", true)
eq(d:rows()[2], "4444", "a mirrored stroke")

group("SpriteTools: fill")
local f = SpriteDoc.new({ w = 5, h = 3, fps = 6, palette = {}, frames = { { "..1..", "..1..", "11..." } } })
SpriteTools.fill(f, 0, 0, "2")
eq(f:rows(), { "221..", "221..", "11..." }, "fill stops at other keys and doesn't cross diagonals")
SpriteTools.fill(f, 4, 2, "3")
eq(f:rows(), { "22133", "22133", "11333" }, "fill spreads through a '.' region")
f:take_changes()
SpriteTools.fill(f, 2, 0, "1")
eq(f:take_changes(), {}, "filling with the same key changes nothing")
SpriteTools.fill(f, 9, 9, "1")
eq(f:rows()[1], "22133", "a fill off the sprite does nothing")

group("SpriteTools: picker")
eq(SpriteTools.pick(f, 0, 0), "2", "pick returns the key under the cell")
eq(SpriteTools.pick(f, 9, 0), nil, "pick off the sprite is nil")
