-- Headless tests for SpriteDoc (apps/sprite/doc.lua).

group("SpriteDoc: blank and palette")
local d = SpriteDoc.blank(4, 3)
eq({ d.s.w, d.s.h, d.s.fps, d:frame_count(), d.frame }, { 4, 3, 6, 1, 1 }, "a blank doc is 4x3, 6 fps, one frame")
eq(d:rows(), { "....", "....", "...." }, "a blank frame is all transparent")
eq({ d.s.palette["0"], d.s.palette["1"], d.s.palette["5"], d.s.palette.f }, { 0x000000, 0xFF0000, 0x00FF00, 0xFFFFFF },
  "default palette: black, the hue wheel, white")
local n = 0
for _ in pairs(d.s.palette) do n = n + 1 end
eq(n, 16, "the default palette has 16 entries")
local loaded = SpriteDoc.new({ w = 1, h = 1, fps = 6, palette = { ["1"] = 0x123456 }, frames = { { "1" } } })
eq({ loaded.s.palette["1"], loaded.s.palette.f }, { 0x123456, 0xFFFFFF }, "a loaded palette keeps its colours and gains the missing defaults")
eq(loaded.dirty, false, "a new doc is not dirty")

group("SpriteDoc: get and set")
d:set(1, 2, "3")
eq(d:get(1, 2), "3", "set then get")
eq(d:rows()[3], ".3..", "set edits one character of the row")
eq(d:take_changes(), { { 1, 2 } }, "the change is recorded")
eq(d:take_changes(), {}, "taking clears the changes")
d:set(1, 2, "3")
eq(d:take_changes(), {}, "setting the same key changes nothing")
d:set(-1, 0, "3"); d:set(4, 0, "3"); d:set(0, 3, "3")
eq(d:take_changes(), {}, "sets off the sprite are ignored")
eq({ d:get(-1, 0), d:get(4, 0) }, {}, "gets off the sprite are nil")

group("SpriteDoc: frames")
d = SpriteDoc.blank(2, 1)
d:set(0, 0, "1")
eq(d:frame_dup(), true, "dup a frame")
eq({ d:frame_count(), d.frame, d:rows()[1] }, { 2, 2, "1." }, "the copy follows the original and is current")
eq(d:frame_add(), true, "add a frame")
eq({ d:frame_count(), d.frame, d:rows()[1] }, { 3, 3, ".." }, "the blank frame goes after the current one")
d:frame_next()
eq(d.frame, 1, "next wraps to the first frame")
d:frame_prev()
eq(d.frame, 3, "prev wraps to the last frame")
for _ = 1, 5 do d:frame_add() end
eq({ d:frame_count(), d:frame_add(), d:frame_dup() }, { 8, false, false }, "8 frames is the limit")
eq(SpriteDoc.blank(1, 1):frame_del(), false, "the only frame can't be deleted")
d.frame = 8
eq(d:frame_del(), true, "delete a frame")
eq({ d:frame_count(), d.frame }, { 7, 7 }, "deleting the last frame steps back one")
local e = SpriteDoc.blank(1, 1)
e:frame_dup()
e:set(0, 0, "2")
eq({ e.s.frames[1][1], e.s.frames[2][1] }, { ".", "2" }, "a duplicated frame is independent")

group("SpriteDoc: undo and redo")
local u = SpriteDoc.blank(2, 1)
u:begin_step(); u:set(0, 0, "1")
eq(u:end_step(), true, "an action that changed something is a step")
u:begin_step()
eq(u:end_step(), false, "an action that changed nothing is not")
eq(u.dirty, true, "a step makes the doc dirty")
u:mark_saved()
eq(u.dirty, false, "mark_saved clears dirty")
u:begin_step(); u:set(1, 0, "2"); u:end_step()
eq(u:undo(), true, "undo")
eq(u:rows()[1], "1.", "undo goes back one step")
eq(u:take_full(), true, "undo asks for a full redraw")
eq(u:undo(), true, "undo again")
eq(u:rows()[1], "..", "back to blank")
eq(u:undo(), false, "nothing more to undo")
eq(u:redo(), true, "redo")
eq(u:rows()[1], "1.", "redo reapplies")
u:begin_step(); u:set(1, 0, "3"); u:end_step()
eq(u:redo(), false, "a new step clears redo")
u:frame_add()
eq(u:frame_count(), 2, "frame add")
u:undo()
eq({ u:frame_count(), u.frame }, { 1, 1 }, "undo removes the added frame")
u:set_color("1", 0x010203)
u:undo()
eq(u.s.palette["1"], 0xFF0000, "undo restores a palette colour")
u:set_fps(99)
eq(u.s.fps, 30, "fps clamps to 30")
u:set_fps(0)
eq(u.s.fps, 1, "fps clamps to 1")
local cap = SpriteDoc.blank(1, 1)
for i = 1, 40 do cap:begin_step(); cap:set(0, 0, i % 2 == 0 and "1" or "2"); cap:end_step() end
local undos = 0
while cap:undo() do undos = undos + 1 end
eq(undos, 32, "the history keeps 32 steps")
